"""Add price_forecasts table

Revision ID: 64feb33cef5d
Revises: 8dcd25359124
Create Date: 2025-12-07 15:42:20.078867

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "64feb33cef5d"
down_revision: str | None = "8dcd25359124"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "price_forecasts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("forecast_date", sa.DateTime(), nullable=False),
        sa.Column("predicted_price", sa.Float(), nullable=False),
        sa.Column("yhat_lower", sa.Float(), nullable=False),
        sa.Column("yhat_upper", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_price_forecasts_id"), "price_forecasts", ["id"], unique=False)
    op.alter_column("items", "url", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("items", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("items", "is_active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("items", "is_refreshing", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("notification_profiles", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("notification_profiles", "apprise_url", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("notification_profiles", "notify_on_price_drop", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("notification_profiles", "notify_on_target_price", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "notification_profiles",
        "price_drop_threshold_percent",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column("notification_profiles", "notify_on_stock_change", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("notification_profiles", "check_interval_minutes", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("price_history", "item_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("price_history", "price", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False)
    op.alter_column("price_history", "timestamp", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.alter_column("settings", "value", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("settings", "value", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("price_history", "timestamp", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column("price_history", "price", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True)
    op.alter_column("price_history", "item_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("notification_profiles", "check_interval_minutes", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("notification_profiles", "notify_on_stock_change", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "notification_profiles",
        "price_drop_threshold_percent",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column("notification_profiles", "notify_on_target_price", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("notification_profiles", "notify_on_price_drop", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("notification_profiles", "apprise_url", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("notification_profiles", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("items", "is_refreshing", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("items", "is_active", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("items", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("items", "url", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_index(op.f("ix_price_forecasts_id"), table_name="price_forecasts")
    op.drop_table("price_forecasts")
    # ### end Alembic commands ###
