"""Add refresh fields

Revision ID: 6ecb6f39fd8c
Revises: initial_migration
Create Date: 2025-11-19 12:53:09.412700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ecb6f39fd8c'
down_revision: Union[str, None] = 'initial_migration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('is_refreshing', sa.Boolean(), nullable=True))
    op.add_column('items', sa.Column('last_error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'last_error')
    op.drop_column('items', 'is_refreshing')
    # ### end Alembic commands ###
