"""add in_stock to price_history

Revision ID: 8dcd25359124
Revises: e8f39c34ae5a
Create Date: 2025-12-06 15:25:38.244351

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8dcd25359124"
down_revision: str | None = "e8f39c34ae5a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("price_history", sa.Column("in_stock", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("price_history", "in_stock")
    # ### end Alembic commands ###
