"""make_item_interval_nullable

Revision ID: 990c59af5ad6
Revises: performance_indexes_v2
Create Date: 2025-11-24 10:01:39.165194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '990c59af5ad6'
down_revision: Union[str, None] = 'performance_indexes_v2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_active_last_checked'), table_name='items')
    op.drop_index(op.f('ix_items_is_active'), table_name='items')
    op.drop_index(op.f('ix_items_last_checked'), table_name='items')
    op.drop_index(op.f('ix_price_history_item_timestamp'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_timestamp'), table_name='price_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_price_history_timestamp'), 'price_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_price_history_item_timestamp'), 'price_history', ['item_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_items_last_checked'), 'items', ['last_checked'], unique=False)
    op.create_index(op.f('ix_items_is_active'), 'items', ['is_active'], unique=False)
    op.create_index(op.f('ix_items_active_last_checked'), 'items', ['is_active', 'last_checked'], unique=False)
    # ### end Alembic commands ###
