"""Add custom_prompt to items

Revision ID: e8f39c34ae5a
Revises: 990c59af5ad6
Create Date: 2025-12-06 13:33:56.909766

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e8f39c34ae5a"
down_revision: str | None = "990c59af5ad6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("custom_prompt", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "custom_prompt")
    # ### end Alembic commands ###
